---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: minimal-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
#spec:
#  ingressClassName: nginx-example
#  rules:
#  - http:
#      paths:
#      - path: /ngingxpath
#        pathType: Prefix
#        backend:
#          service:
#            name: test
#            port:
#              number: 80
#---
#apiVersion: vpcresources.k8s.aws/v1beta1
#kind: SecurityGroupPolicy
#metadata:
#  name: my-security-group-policy
#  namespace: my-namespace
#spec:
#  podSelector: 
#    matchLabels:
#      role: my-role
#  securityGroups:
#    groupIds:
#      - sg-abc123